services:
  postgres:
    image: postgres:14.13-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres

  engine:
    image: ghcr.io/noumenadigital/images/engine:latest
    ports:
      - "11000:11000"
      - "12000:12000"
      - "12400:12400"
      - "12700:12700"
    environment:
      ENGINE_DB_PASSWORD: postgres
      ENGINE_DEV_MODE: true
