name: "Bump parent-pom version"
on:
  workflow_dispatch:
    inputs:
      PLATFORM_VERSION:
        description: "Version of platform to use for parent-pom"
        required: true
env:
  CI_PIPELINE_URL: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
  MAVEN_CLI_OPTS: "-s ${{ github.workspace }}/.m2/settings.xml --batch-mode"
  MAVEN_OPTS: >-
    -Dorg.slf4j.simpleLogger.showDateTime=true 
    -Dorg.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss.SSS
    -Dmaven.wagon.httpconnectionManager.ttlSeconds=60
  GITHUB_REPO_USER: "${{ secrets.GH_USERNAME }}"
  GITHUB_REPO_PASS: "${{ secrets.GH_PASSWORD }}"

jobs:
  bump-parent-version:
    env:
      SLACK_WEBHOOK: ${{ secrets.SLACK_URL }}
      SLACK_USERNAME: "bumperBot"
      SLACK_ICON: "https://avatars.githubusercontent.com/u/56019787?s=50&v=4"
      SLACK_CHANNEL: "#platform-status"
      SLACK_FOOTER: "npl-starter#bump-parent-version.yml"
      MSG_MINIMAL: true

    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Set up Java"
        uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: "17"
          cache: "maven"

      - name: "Update parent-pom version"
        run: "mvn $MAVEN_CLI_OPTS versions:update-parent -DgenerateBackupPoms=false -DparentVersion=[${{ inputs.PLATFORM_VERSION }}]"

      - name: "Verify with new version"
        run: "mvn $MAVEN_CLI_OPTS clean verify"

      - name: "Create pull request"
        uses: peter-evans/create-pull-request@v4
        id: cpr
        with:
          title: "Bump platform version to ${{ inputs.PLATFORM_VERSION }}"
          commit-message: "Updated platform version to ${{ inputs.PLATFORM_VERSION }}"
          branch: "Bump-platform-${{ inputs.PLATFORM_VERSION }}"
          delete-branch: true

      - name: "Approve pull request"
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: juliangruber/approve-pull-request-action@v2
        with:
          number: ${{ steps.cpr.outputs.pull-request-number }}
          github-token: ${{ secrets.GH_PASSWORD }}

      - name: "Notify Platform about PR"
        if: ${{ steps.cpr.outputs.pull-request-operation == 'created' }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: "NPL Starter platform version upgraded successfully"
          SLACK_MESSAGE: "Merge <${{ steps.cpr.outputs.pull-request-url }}|#${{ steps.cpr.outputs.pull-request-number }}> to bump the NPL starter to platform version ${{ inputs.PLATFORM_VERSION }}."

      - name: "Report build failed"
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: "NPL Starter platform version upgrade failed"
          SLACK_MESSAGE: "The <${{ env.CI_PIPELINE_URL }}|npl-starter build> failed for platform release ${{ inputs.PLATFORM_VERSION }}."
