name: "Bump platform version"

on:
  workflow_dispatch:
    inputs:
      PLATFORM_VERSION:
        description: "Platform version to build the project with"
        required: true

env:
  GITHUB_REPO_USER: "${{ secrets.GH_USERNAME }}"
  GITHUB_REPO_PASS: "${{ secrets.GH_PASSWORD }}"
  MAVEN_CLI_OPTS: "-s ${{ github.workspace }}/.m2/settings.xml --batch-mode"
  MAVEN_OPTS: >-
    -Dorg.slf4j.simpleLogger.showDateTime=true 
    -Dorg.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss.SSS
    -Dmaven.wagon.httpconnectionManager.ttlSeconds=60

  CI_PIPELINE_URL: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
  PLATFORM_VERSION_TAG_LINK: "https://github.com/NoumenaDigital/platform/releases/tag/${{ inputs.PLATFORM_VERSION }}"
  SLACK_WEBHOOK: "${{ secrets.SLACK_URL }}"
  SLACK_USERNAME: "bumperBot"
  SLACK_ICON: "https://avatars.githubusercontent.com/u/56019787?s=50&v=4"
  SLACK_CHANNEL: "#platform-status"
  SLACK_TITLE: " " # needs to be a space rather than omitted in order to suppress the title
  SLACK_FOOTER: "npl-starter#bump-platform-version.yml"
  MSG_MINIMAL: true

jobs:
  build_test_verify:
    name: "Build project with platform version"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Set up Java"
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: "17"
          cache: "maven"

      - name: "Update parent-pom version"
        run: "mvn $MAVEN_CLI_OPTS versions:update-parent -DgenerateBackupPoms=false -DparentVersion=[${{ inputs.PLATFORM_VERSION }}]"

      - name: "Verify with platform version"
        run: "mvn $MAVEN_CLI_OPTS clean verify"

      - name: "Create pull request"
        uses: peter-evans/create-pull-request@v4
        id: cpr
        with:
          title: "Bump platform version to ${{ inputs.PLATFORM_VERSION }}"
          commit-message: "Updated platform version to ${{ inputs.PLATFORM_VERSION }}"
          branch: "Bump-platform-${{ inputs.PLATFORM_VERSION }}"
          delete-branch: true

      - name: "Approve pull request"
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: juliangruber/approve-pull-request-action@v2
        with:
          number: ${{ steps.cpr.outputs.pull-request-number }}
          github-token: ${{ secrets.GH_PASSWORD }}

      - name: "Report action required"
        if: ${{ steps.cpr.outputs.pull-request-operation == 'created' }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: "Action required"
          SLACK_MESSAGE: "Please merge <${{ steps.cpr.outputs.pull-request-url }}|npl-starter PR #${{ steps.cpr.outputs.pull-request-number }}> to bump the platform version to <${{ env.PLATFORM_VERSION_TAG_LINK }}|${{ inputs.PLATFORM_VERSION }}>."
          SLACK_COLOR: "660033"

      - name: "Report failure"
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_MESSAGE: "The <${{ env.CI_PIPELINE_URL }}|npl-starter build> failed for platform release <${{ env.PLATFORM_VERSION_TAG_LINK }}|${{ inputs.PLATFORM_VERSION }}>."
          SLACK_COLOR: ${{ job.status }}

      - name: "Report cancellation"
        if: ${{ cancelled() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_MESSAGE: "The <${{ env.CI_PIPELINE_URL }}|npl-starter build> cancelled for platform release <${{ env.PLATFORM_VERSION_TAG_LINK }}|${{ inputs.PLATFORM_VERSION }}>."
          SLACK_COLOR: ${{ job.status }}
