name: "Bump platform version"

on:
  workflow_dispatch:
    inputs:
      PLATFORM_VERSION:
        description: "Platform version to build the project with"
        required: true

env:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: >-
    -Dorg.slf4j.simpleLogger.showDateTime=true 
    -Dorg.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss.SSS
    -Dmaven.wagon.httpconnectionManager.ttlSeconds=60

  CI_PIPELINE_URL: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
  PLATFORM_VERSION_TAG_LINK: "https://github.com/NoumenaDigital/platform/releases/tag/${{ inputs.PLATFORM_VERSION }}"

jobs:
  build_test_verify:
    name: "Build project with platform version"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Set up Java"
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: "17"
          cache: "maven"

      - name: "Update parent-pom version"
        run: "mvn $MAVEN_CLI_OPTS versions:update-parent -DgenerateBackupPoms=false -DparentVersion=[${{ inputs.PLATFORM_VERSION }}]"

      - name: "Verify with platform version"
        run: "mvn $MAVEN_CLI_OPTS clean verify"

      - name: "Create pull request"
        uses: peter-evans/create-pull-request@v4
        id: cpr
        with:
          title: "Bump platform version to ${{ inputs.PLATFORM_VERSION }}"
          commit-message: "Updated platform version to ${{ inputs.PLATFORM_VERSION }}"
          branch: "Bump-platform-${{ inputs.PLATFORM_VERSION }}"
          delete-branch: true
