name: "Verify PR"

on:
  pull_request

env:
  GITHUB_REPO_USER: "${{ secrets.GH_USERNAME }}"
  GITHUB_REPO_PASS: "${{ secrets.GH_PASSWORD }}"
  MAVEN_CLI_OPTS: "-s ${{ github.workspace }}/.m2/settings.xml --batch-mode"
  MAVEN_OPTS: >-
    -Dorg.slf4j.simpleLogger.showDateTime=true 
    -Dorg.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss.SSS
    -Dmaven.wagon.httpconnectionManager.ttlSeconds=60

# todo 22 experimental
  CI_PIPELINE_URL: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
  SLACK_WEBHOOK: "${{ secrets.SLACK_URL }}"
  SLACK_USERNAME: "bumperBot"
  SLACK_ICON: "https://avatars.githubusercontent.com/u/56019787?s=50&v=4"
  SLACK_CHANNEL: "#platform-status"
  SLACK_TITLE: " " # needs to be a space rather than omitted in order to suppress the title
  SLACK_FOOTER: "npl-starter#xxx.yml"
  MSG_MINIMAL: true

jobs:
  build-test-verify:
    if: ${{ false }}
    name: "Build and test"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Set up Java"
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: "17"
          cache: "maven"

      - name: "Verify"
        run: "mvn $MAVEN_CLI_OPTS clean verify"

  # todo 22 experimental
  send-failure-notification:
    name: "Report failure"
    runs-on: "ubuntu-latest"
    if: ${{ failure() || cancelled() && !false  }}

    needs:
      - build-test-verify

    steps:
      - name: "Send slack notification"
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_MESSAGE: "The <${{ env.CI_PIPELINE_URL }}|xxx build> failed ..."
          SLACK_COLOR: "failure"
